CL-25 Setup a mock GPS device
clowder-cloud/mock_device pull request #1
Opened 2024-11-20 13:58 UTC by stevelw

2024-11-21 10:38 UTC, jeepies requested changes

2024-11-21 10:38 UTC, jeepies commented on tsconfig.json
> +  "include": ["src/**/*", "src/**/*.json"]
JSON file was not included into the "dist" folder

2024-11-21 10:38 UTC, jeepies commented on src/device.ts
> +  return network.post("/cats/location", body);
should be requesting "/api/devices/update"

2024-11-21 10:38 UTC, jeepies commented on testData/cat_1.json
As per our backend, trackingData should contain an array of { id: "string", lat: number, lon: number  }

2024-11-25 15:13 UTC, jeepies commented
The issue with this is that a device with, for example, ID 9000001 doesnt exist on our backend - We should rewrite this so it does a request to create a device, then sends all the data with the device_id being the result of the create request. Otherwise the backend will try to search for device with ID 9000001 and then error

2024-11-25 15:41 UTC, stevelw commented
@jeepies that sounds like a backend issue not a mock issue? Shouldn't we just add the needed IDs to the database seeding for dev environment?

2024-11-25 16:10 UTC, jeepies commented
> @jeepies that sounds like a backend issue not a mock issue? Shouldn't we just add the needed IDs to the database seeding for dev environment?

The issue with that is all our ID's on the backend are collision resistant unique id's (cuid), not integers. I think at this point in development, it'd be easier to migrate the mock device ID's over.

2024-11-25 20:15 UTC, stevelw commented
I've added the valid device IDs from our database to the dataset (by default only the first one is used).

When I run I get a write permissions error. I got that before but I thought you'd got it working with our backend when you last tested? Can you replicate?

2024-11-25 20:27 UTC, jeepies commented
I'm only getting an error because `accuracy` should be a number, but its defined as `"TBD"`. Do you have a screenshot of the error you're getting?

2024-11-25 21:09 UTC, stevelw commented
![image](https://github.com/user-attachments/assets/3d196f82-c963-4ec3-8931-d8399ce9457a)

2024-11-25 21:10 UTC, stevelw commented
...
![image](https://github.com/user-attachments/assets/ee5f70b4-e5be-472b-89da-a6733bf7e218)

2024-11-25 21:11 UTC, jeepies commented
> ![image](https://private-user-images.githubusercontent.com/19916119/389703034-3d196f82-c963-4ec3-8931-d8399ce9457a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NjkzMzcsIm5iZiI6MTczMjU2OTAzNywicGF0aCI6Ii8xOTkxNjExOS8zODk3MDMwMzQtM2QxOTZmODItYzk2My00ZWMzLTg5MzEtZDgzOTljZTk0NTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDIxMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZDZjYjdlZjI2MmU0NjgwZWU4OTUzMjU3OTYzOWI1MDUxNzMxYjk4NWEyOGI2MjVmMGY2NGU2MjA4MjQ2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xlr5U2b7fpTH9UG9cNtT9G56K7O6D3rOXs6hUHPKHng)

There's your issue - Change your `.env` to `http` - We don't have a certificate for localhost!

2024-11-25 21:46 UTC, stevelw commented
> There's your issue - Change your `.env` to `http` - We don't have a certificate for localhost!

I couldn't see you image, but the .env edit did fix it.

I've done https://github.com/clowder-cloud/backend/pull/24 to fix the accuracy data issue - we don't know it will be a number, and if we're not using it anywhere it's better to just not check it.

2024-11-26 10:43 UTC, guarde approved these changes

2024-11-26 10:43 UTC, merged